/**
 * Corpus drift gate: the freshly computed Merkle root must equal the
 * committed lock file. Mirrors packages/corpus-us-federal/test/lock.test.ts.
 *
 * Phase 1 note: this corpus has ZERO rules, so `lock.rules` is `{}` and the
 * entire signal lives in `merkleRoot` — core's merkleRoot() adds one leaf for
 * the fact catalog (fact DEFAULTS change answers, so they are pinned too, see
 * packages/core/src/hash.ts). The lock is therefore already meaningful: any
 * edit to src/facts.ts moves the root and fails this test until
 * `pnpm -F @opencantax/corpus-ca-federal gen:lock` is rerun.
 *
 * The corpus is imported from ../src (not the package name): this package is
 * INERT BY DESIGN — it declares no "build" script, so `pnpm -r build` skips it
 * and ./dist may not exist. Vitest compiles the TypeScript sources directly.
 *
 * corpus.lock.json may not exist yet (it is generated by scripts/gen-lock.mjs,
 * which needs a dist). Until it does, the first test below fails LOUDLY with
 * the command to run, and the hash comparisons are skipped rather than
 * reported as a cascade of confusing errors. A missing lock is deliberately
 * NOT treated as "passing" — an unpinned corpus is exactly what this gate
 * exists to catch.
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { loadCorpus } from "@invaro/opentax-core";
import { describe, expect, it } from "vitest";
import { DEFAULT_TARGET, corpusInput, getCorpus } from "../src/index.js";

interface Lock {
  name: string;
  version: string;
  merkleRoot: string;
  /**
   * Present in this corpus's lock (not the US one): the declared default
   * target. Recorded rather than hashed — see the note in gen-lock.mjs.
   */
  defaultTarget?: string;
  ruleCount: number;
  /** Present in this corpus's lock (not the US one): fact-catalog size. */
  factCount?: number;
  rules: Record<string, string>;
}

const lockPath = path.join(import.meta.dirname, "..", "corpus.lock.json");
const lockExists = existsSync(lockPath);
const lock: Lock | null = lockExists
  ? (JSON.parse(readFileSync(lockPath, "utf8")) as Lock)
  : null;

describe("corpus.lock.json", () => {
  const corpus = getCorpus();

  it("the lock file is committed", () => {
    expect(
      lockExists,
      `${lockPath} is missing — run \`pnpm -F @opencantax/corpus-ca-federal gen:lock\` and commit the result`,
    ).toBe(true);
  });

  it.runIf(lockExists)("merkle root matches the committed lock", () => {
    expect(corpus.merkleRoot).toBe(lock!.merkleRoot);
  });

  // DEFAULT_TARGET is the question the CLI answers when the caller names
  // none, so silently repointing it changes what the engine is FOR. It is
  // not a merkle leaf (core hashes rules + facts only), so without this gate
  // a retarget moves no hash and shows up nowhere in review.
  it.runIf(lockExists)("the default target matches the committed lock", () => {
    expect(
      lock!.defaultTarget,
      "corpus.lock.json has no defaultTarget — regenerate with `pnpm -F @opencantax/corpus-ca-federal gen:lock`",
    ).toBeDefined();
    expect(DEFAULT_TARGET).toBe(lock!.defaultTarget);
  });

  it.runIf(lockExists)("every rule hash matches the committed lock", () => {
    expect(Object.fromEntries(corpus.ruleHashes)).toEqual(lock!.rules);
  });

  it.runIf(lockExists)("rule count matches", () => {
    expect(corpus.rules.length).toBe(lock!.ruleCount);
  });

  it.runIf(lockExists)("fact count matches", () => {
    // Phase 1: the fact catalog is the only moving part of the hash, so an
    // unchanged root with a changed fact count would mean the leaf is not
    // actually covering the catalog.
    expect(lock!.factCount, "lock is missing factCount").toBeTypeOf("number");
    expect(corpus.facts.length).toBe(lock!.factCount);
  });

  it.runIf(lockExists)("lock identifies this corpus", () => {
    expect(lock!.name).toBe(corpus.name);
    expect(lock!.version).toBe(corpus.version);
  });

  it("the corpus identity matches package.json", () => {
    // corpus.name is stamped into every proof artifact (proof.corpus.name),
    // so it has to name a package that actually exists. This drifted once
    // already: the H2 rename moved package.json to @opencantax while
    // src/index.ts kept the old @woodgate scope, which the lock then baked
    // in. Compared, not hardcoded, so a future rename only has to touch
    // package.json and src/index.ts.
    const pkg = JSON.parse(
      readFileSync(path.join(import.meta.dirname, "..", "package.json"), "utf8"),
    ) as { name: string; version: string };
    expect(corpus.name).toBe(pkg.name);
    expect(corpus.version).toBe(pkg.version);
  });

  it("merkle root is a well-formed sha256 digest", () => {
    expect(corpus.merkleRoot).toMatch(/^sha256:[0-9a-f]{64}$/);
  });

  it("the merkle root is stable across loads", () => {
    // getCorpus() caches, so comparing getCorpus() to itself would be a
    // tautology — load fresh to prove the root does not depend on the cache.
    expect(loadCorpus(corpusInput).merkleRoot).toBe(corpus.merkleRoot);
  });
});
